fullscript_dbt_project:
  outputs:
    dev:
      account: **************
      database: FULLSCRIPT
      password: **********
      role: ACCOUNTADMIN
      schema: Retail
      threads: 1
      type: snowflake
      user: kv3singh
      warehouse: COMPUTE_WH
  target: dev
